[package]
name = "spawn-asset"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
shared.workspace = true
eldenring.workspace = true
eldenring-util.workspace = true
nalgebra-glm = "0.19.0"
